name: Build and Push Docker Image

on:
  push:
    branches: [ '**' ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
  # Enable manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        run: |
          # Install dependencies if needed
          sudo apt-get update
          sudo apt-get install -y curl

          # Create Docker config directory if it doesn't exist
          mkdir -p ~/.docker/cli-plugins/

          # Download Docker Buildx binary
          curl -L "https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64" -o ~/.docker/cli-plugins/docker-buildx
    
          # Make it executable
          chmod +x ~/.docker/cli-plugins/docker-buildx
    
          # Create and use a new builder instance
          docker buildx create --name mybuilder --use
    
          # Inspect to verify it's working
          docker buildx inspect --bootstrap
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/clock-app
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max