name: Build and Push Docker Image

on:
  push:
    branches: [ '**' ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
  # Enable manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        run: |
          # Install dependencies if needed
          sudo apt-get update
          sudo apt-get install -y curl jq

          # Install Docker CLI plugins directory if it doesn't exist
          mkdir -p ~/.docker/cli-plugins/
          
          # Download the latest buildx binary
          BUILDX_URL=$(curl -s https://api.github.com/repos/docker/buildx/releases/latest | jq -r '.assets[] | select(.name | contains("linux-amd64")) | .browser_download_url')
          curl -sSL "$BUILDX_URL" -o ~/.docker/cli-plugins/docker-buildx
          
          # Set executable permissions
          chmod +x ~/.docker/cli-plugins/docker-buildx
          
          # Create a new builder instance
          docker buildx create --name mybuilder --use
          
          # Verify installation
          docker buildx version      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/clock-app
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max